"""10.05 — The multivariate Kalman filter: state [x, v], two sensors, and consistency checks.

    python 10-localization/code/kf_multivariate.py              # YOUR labs/exercises/10.05/student.py
    python 10-localization/code/kf_multivariate.py --solution   # the reference

1. One predict + update by the numbers (the FM.07 example continued).
2. karmel drives toward the wall at x = 4 m. Filter A uses the ToF only (position); filter B also
   fuses the encoder wheel speed (velocity). RMSE, NIS and NEES for both.
3. Consistency: 50 Monte Carlo runs of a model-exact simulation with Q correct, 100x too small,
   100x too large. Average NEES against the 95% chi-square band.
4. The encoder-noise trap: NIS says the encoder is quieter than assumed; believing that (sigma_v =
   1 cm/s) makes NEES say the filter is overconfident.
"""

from __future__ import annotations

import argparse
import math

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

import loc_common as lc  # noqa: E402

RANGE_X = 0.125                 # ToF mount x in base_link (karmel.yaml sensors.range_front.x_m)
TOF_STD = 0.03                  # m
ACCEL_STD = 0.3                 # m/s^2, the constant-velocity model's process noise
NEES_BOUNDS_50_RUNS_2D = (1.4844, 2.5912)  # scipy.stats.chi2.ppf([0.025, 0.975], 100) / 50
SETTLE = 20


def fuse_run(ex, ws, run, use_encoder: bool, encoder_std: float = 0.03) -> dict:
    x_true = ws.ROOM_W - RANGE_X - run.truth
    dt = float(run.t[1] - run.t[0])
    F, Q = ex.constant_velocity_model(dt, ACCEL_STD)
    kf = ex.KalmanFilter([0.5, 0.0], np.diag([0.05**2, 0.05**2]))
    est, cov, nis_tof, nis_enc, nees = [], [], [], [], []
    for k, (z, speed) in enumerate(zip(run.measurements, run.wheel_speed)):
        kf.predict(F, Q)
        if use_encoder:
            kf.update([speed], [[0.0, 1.0]], [[encoder_std**2]])
            nis_enc.append(ex.nis(kf.nu, kf.S))
        if z is not None:
            kf.update([ws.ROOM_W - RANGE_X - z], [[1.0, 0.0]], [[TOF_STD**2]])
            nis_tof.append(ex.nis(kf.nu, kf.S))
        est.append(kf.x.copy())
        cov.append(kf.P.copy())
        nees.append(ex.nees([x_true[k], run.velocity[k]], kf.x, kf.P))
    est, cov = np.array(est), np.array(cov)
    z = np.array([np.nan if m is None else ws.ROOM_W - RANGE_X - m for m in run.measurements])
    valid = ~np.isnan(z)
    return {
        "est": est, "cov": cov, "x_true": x_true,
        "pos_rmse": float(np.sqrt(np.mean((est[SETTLE:, 0] - x_true[SETTLE:]) ** 2))),
        "vel_rmse": float(np.sqrt(np.mean((est[SETTLE:, 1] - run.velocity[SETTLE:]) ** 2))),
        "tof_rmse": float(np.sqrt(np.mean((z[valid][SETTLE:] - x_true[valid][SETTLE:]) ** 2))),
        "nis_tof": float(np.mean(nis_tof)), "nis_enc": float(np.mean(nis_enc)) if nis_enc else float("nan"),
        "nees": float(np.mean(nees[SETTLE:])),
    }


def monte_carlo_nees(ex, q_scale: float, runs: int = 50, steps: int = 100, seed: int = 2024) -> np.ndarray:
    """Truth generated by the constant-velocity model itself; the filter assumes Q * q_scale."""
    dt, accel_std, r_std = 0.1, 0.5, 0.05
    F, Q = ex.constant_velocity_model(dt, accel_std)
    G = np.array([0.5 * dt * dt, dt])
    rng = np.random.default_rng(seed)
    P0 = np.diag([0.1**2, 0.1**2])
    out = np.zeros((runs, steps))
    for r in range(runs):
        x = np.array([0.0, 0.3])
        kf = ex.KalmanFilter(x + rng.multivariate_normal([0.0, 0.0], P0), P0)
        for k in range(steps):
            x = F @ x + G * rng.normal(0.0, accel_std)
            kf.predict(F, Q * q_scale)
            kf.update([x[0] + rng.normal(0.0, r_std)], [[1.0, 0.0]], [[r_std**2]])
            out[r, k] = ex.nees(x, kf.x, kf.P)
    return out.mean(axis=0)


def main(argv: list[str] | None = None) -> dict:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--solution", action="store_true")
    ap.add_argument("--out", default="localization_out")
    ap.add_argument("--seed", type=int, default=2)
    args = ap.parse_args(argv)
    out = lc.out_dir(args.out)
    ex = lc.load_exercise("10.05", solution=args.solution)
    ws = lc.load_provided("10.04", "wall_sim")
    np.set_printoptions(precision=6, suppress=True)
    results: dict = {}

    # 1. by the numbers -----------------------------------------------------------------------------
    print("1) x = [1.0 m, 0.5 m/s], P = diag(0.04, 0.01), dt = 0.1 s, Q = 0; ToF says x = 1.10 m (R = 0.01)")
    kf = ex.KalmanFilter([1.0, 0.5], np.diag([0.04, 0.01]))
    F = np.array([[1.0, 0.1], [0.0, 1.0]])
    x_pred, P_pred = kf.predict(F, np.zeros((2, 2)))
    print(f"   predict: x = {x_pred}, P = {P_pred.tolist()}")
    x_upd, P_upd = kf.update([1.10], [[1.0, 0.0]], [[0.01]])
    print(f"   update:  nu = {kf.nu}, S = {kf.S.tolist()}, K = {kf.K.ravel()}")
    print(f"            x = {x_upd}, P = {np.round(P_upd, 8).tolist()}")
    results["by_hand"] = {"x_pred": x_pred, "P_pred": P_pred, "K": kf.K, "x": x_upd, "P": P_upd}

    # 2. the simulated robot ------------------------------------------------------------------------
    run = ws.drive_to_wall(args.seed, realistic=True, range_noise_std_m=TOF_STD)
    a = fuse_run(ex, ws, run, use_encoder=False)
    b = fuse_run(ex, ws, run, use_encoder=True)
    print(f"\n2) Seed {args.seed}, ToF sigma 3 cm at 20 Hz, accel_std {ACCEL_STD} m/s^2")
    print(f"   ToF alone as a position: RMSE {a['tof_rmse'] * 1000:.1f} mm")
    for name, r in (("A: ToF only      ", a), ("B: ToF + encoders", b)):
        print(f"   {name}: position RMSE {r['pos_rmse'] * 1000:5.1f} mm, velocity RMSE {r['vel_rmse'] * 100:4.1f} cm/s, "
              f"NIS(ToF) {r['nis_tof']:.2f}, NIS(enc) {r['nis_enc']:.2f}, NEES {r['nees']:.2f}")
    results["sim"] = {"tof_only": {k: v for k, v in a.items() if k not in ("est", "cov", "x_true")},
                      "fused": {k: v for k, v in b.items() if k not in ("est", "cov", "x_true")}}

    fig, axes = plt.subplots(2, 1, figsize=(9, 6), sharex=True)
    for r, color, label in ((a, "tab:orange", "A: ToF only"), (b, "tab:blue", "B: ToF + encoders")):
        err = r["est"][:, 0] - r["x_true"]
        band = 2 * np.sqrt(r["cov"][:, 0, 0])
        axes[0].plot(run.t, err * 1000, color=color, label=label)
        axes[0].fill_between(run.t, -band * 1000, band * 1000, color=color, alpha=0.15)
        axes[1].plot(run.t, r["est"][:, 1], color=color, label=label)
    axes[0].set_ylim(-60, 60)
    axes[0].set_ylabel("position error (mm), +/-2 sigma band")
    axes[1].plot(run.t, run.velocity, color="black", label="true velocity")
    axes[1].set_ylabel("velocity (m/s)")
    axes[1].set_xlabel("time (s)")
    axes[0].legend()
    axes[1].legend()
    fig.tight_layout()
    fig.savefig(out / "kf_multivariate_run.png", dpi=120)
    plt.close(fig)

    # 3. NEES consistency ---------------------------------------------------------------------------
    lo, hi = NEES_BOUNDS_50_RUNS_2D
    print(f"\n3) Monte Carlo NEES (50 runs x 100 steps, n = 2, 95% band for the average [{lo:.2f}, {hi:.2f}])")
    fig, ax = plt.subplots(figsize=(7, 4))
    results["nees"] = {}
    for q_scale, color in ((0.01, "tab:red"), (1.0, "tab:green"), (100.0, "tab:blue")):
        avg = monte_carlo_nees(ex, q_scale)
        inside = float(np.mean((avg > lo) & (avg < hi)))
        verdict = "consistent" if lo < avg.mean() < hi else ("OVERconfident" if avg.mean() > hi else "UNDERconfident")
        print(f"   Q x {q_scale:<6g}: mean NEES {avg.mean():6.2f}, steps inside band {inside * 100:5.1f}%  -> {verdict}")
        results["nees"][q_scale] = {"mean": float(avg.mean()), "inside": inside}
        ax.semilogy(avg, color=color, label=f"Q x {q_scale:g}")
    ax.axhspan(lo, hi, color="tab:gray", alpha=0.3, label="95% band")
    ax.set_xlabel("time step")
    ax.set_ylabel("average NEES")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out / "kf_nees.png", dpi=120)
    plt.close(fig)

    # 4. the encoder-noise trap ---------------------------------------------------------------------
    print("\n4) How noisy is the encoder speed? (same run, filter B)")
    results["encoder_std"] = {}
    for enc_std in (0.01, 0.03, 0.1):
        r = fuse_run(ex, ws, run, use_encoder=True, encoder_std=enc_std)
        print(f"   sigma_v = {enc_std * 100:4.1f} cm/s: NIS(enc) {r['nis_enc']:.2f}, NIS(ToF) {r['nis_tof']:.2f}, "
              f"NEES {r['nees']:.2f}, position RMSE {r['pos_rmse'] * 1000:.1f} mm")
        results["encoder_std"][enc_std] = {k: v for k, v in r.items() if k not in ("est", "cov", "x_true")}
    print(f"wrote {out / 'kf_multivariate_run.png'} and {out / 'kf_nees.png'}")
    return results


if __name__ == "__main__":
    main()
